"""default added to the likes and dislikes

Revision ID: 37ab86e0da42
Revises: 4a9e8f585d8c
Create Date: 2024-02-27 20:07:17.685033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ab86e0da42'
down_revision: Union[str, None] = '4a9e8f585d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
