"""blog image relationship

Revision ID: 8081e726daa4
Revises: dbcb16deac98
Create Date: 2024-04-07 16:37:42.452382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8081e726daa4'
down_revision: Union[str, None] = 'dbcb16deac98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'thumbnail_id')
    op.add_column('images', sa.Column('blog', sa.Integer(), nullable=False))
    op.drop_constraint('images_poster_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'blogs', ['blog'], ['id'])
    op.drop_column('images', 'poster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('poster_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_poster_id_fkey', 'images', 'users', ['poster_id'], ['id'])
    op.drop_column('images', 'blog')
    op.add_column('blogs', sa.Column('thumbnail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
