"""changed name to text in Tag

Revision ID: 871fb898e8e4
Revises: f9037fbf5b1c
Create Date: 2024-03-15 19:44:25.683414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871fb898e8e4'
down_revision: Union[str, None] = 'f9037fbf5b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('text', sa.String(), nullable=False))
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    op.create_unique_constraint(None, 'tags', ['text'])
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_unique_constraint('tags_name_key', 'tags', ['name'])
    op.drop_column('tags', 'text')
    # ### end Alembic commands ###
