"""modified table blog

Revision ID: 8db343c9a34d
Revises: 4045e8b9c036
Create Date: 2024-04-09 01:25:29.205118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db343c9a34d'
down_revision: Union[str, None] = '4045e8b9c036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_constraint('images_blog_id_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'blog_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('images_blog_id_fkey', 'images', 'blogs', ['blog_id'], ['id'])
    op.drop_column('blogs', 'thumbnail_url')
    # ### end Alembic commands ###
