"""added user_actions_table

Revision ID: a61174d72c1a
Revises: 7e71de86a394
Create Date: 2024-03-24 02:49:09.583605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61174d72c1a'
down_revision: Union[str, None] = '7e71de86a394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_actions',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('blog_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_actions')
    # ### end Alembic commands ###
