"""updated blog

Revision ID: eba52f6bc61c
Revises: a61174d72c1a
Create Date: 2024-03-24 23:30:53.263523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba52f6bc61c'
down_revision: Union[str, None] = 'a61174d72c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('thumbnail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'thumbnails', ['thumbnail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'thumbnail_id')
    op.drop_table('thumbnails')
    # ### end Alembic commands ###
