"""changed name to text in Tag

Revision ID: f9037fbf5b1c
Revises: a6b8a19be8f7
Create Date: 2024-03-14 23:51:27.758219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9037fbf5b1c'
down_revision: Union[str, None] = 'a6b8a19be8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
